# .readthedocs.yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # Step 1: Install your main project and its dependencies (from setup.py)
    - method: pip
      path: .
    # Step 2: Install your documentation-specific dependencies
    - requirements: docs/requirements.txt
